version: '3'
services:
  my-app:
    image: my-go-app:latest
    ports:
      - "8080:8080"
    environment:
      - DAPR_PERF_METRICS_PROMETHEUS_URL=http://prometheus-pushgateway.dapr-perf-metrics.svc.cluster.local:9091