{
 "title": "Dapr_Perf_Test_1",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "perf_test", "query": { "query": "label_values(perf_test)" } }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "BASELINE_RESPONSE_TIME{perf_test=\"$perf_test\"}"
    },
    {
     "expr": "DAPR_RESPONSE_TIME{perf_test=\"$perf_test\"}"
    },
    {
     "expr": "LATENCY_BY_DAPR{perf_test=\"$perf_test\"}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "APPLICATION_THROUGHPUT{perf_test=\"$perf_test\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "milliCPU" } },
   "targets": [
    {
     "expr": "APP_CPU_USAGE{perf_test=\"$perf_test\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "APP_MEMORY_USAGE{perf_test=\"$perf_test\"}"
    }
   ]
  },
  { "title": "Dapr Sidecar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "milliCPU" } },
   "targets": [
    {
     "expr": "DAPR_SIDECAR_CPU_USAGE{perf_test=\"$perf_test\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DAPR_SIDECAR_MEMORY_USAGE{perf_test=\"$perf_test\"}"
    }
   ]
  }
 ]
}