name: Go

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Run Go
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Go
      run: go run hello.go